# For more information: https://laravel.com/docs/sail
version: "3"
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    command: "npm run dev"
    ports:
      - 3000:3000
    depends_on:
      - movie_db

  movie_db:
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: movie
      MYSQL_USER: movie
      MYSQL_PASSWORD: movie
      MYSQL_ROOT_PASSWORD: movie
    volumes:
      - ./database/dbdata:/var/lib/mysql
    ports:
      - 3306:3306
